#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# REMOVE SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Removing system configurations related to $app..."

if ynh_hide_warnings yunohost service status "$app" >/dev/null; then
	yunohost service remove "$app"
fi

ynh_config_remove_nginx

ynh_systemctl --service="$app" --action="stop"

#=================================================
# UNINSTALLING NETDATA
#=================================================
ynh_script_progression "Uninstalling Netdata..."

# Kill all netdata processes (essentially what the official uninstaller does)
pkill netdata
pkill -U netdata

# Rm all files that netdata may have installed (this is copypasta of the official uninstaller script)
ynh_safe_rm /etc/logrotate.d/netdata
ynh_safe_rm /etc/systemd/system/netdata.service
ynh_safe_rm /lib/systemd/system/netdata.service
ynh_safe_rm /usr/lib/systemd/system/netdata.service
ynh_safe_rm /etc/init.d/netdata
ynh_safe_rm /etc/periodic/daily/netdata-updater
ynh_safe_rm /etc/cron.daily/netdata-updater
ynh_safe_rm "/usr/sbin/netdata"
ynh_safe_rm "/usr/share/netdata"
ynh_safe_rm "/usr/libexec/netdata"
ynh_safe_rm "/var/lib/netdata"
ynh_safe_rm "/var/cache/netdata"
ynh_safe_rm "/etc/netdata"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Removal of $app completed"
