#!/bin/bash

# Note: each files and directories you've saved using the ynh_backup helper
# will be located in the current directory, regarding the last argument.

# Exit on command errors and treat unset variables as an error
set -eu

app=$YNH_APP_INSTANCE_NAME

# Source YunoHost helpers
source /usr/share/yunohost/helpers

# Retrieve old app settings
domain=$(ynh_app_setting_get "$app" domain)
path=$(ynh_app_setting_get "$app" path)

# Source local helpers
source ./conf/_common.sh
SRCPATH=$(pwd)

# Fix path if needed
path=$(fix_path $path)

# Check domain/path availability
sudo yunohost app checkurl "${domain}${path}" -a "$app" \
    || ynh_die "Path not available: ${domain}${path}"
    
# Download and extract application 
TMPDIR=$(extract_application)

# Install dependencies
ynh_package_update
ynh_package_install zlib1g-dev uuid-dev libmnl-dev gcc make git autoconf autoconf-archive autogen automake pkg-config curl jq nodejs

# Launch netdata installation in /opt directory
cd $TMPDIR
sudo ./netdata-installer.sh --install /opt --dont-wait
sudo mv ./netdata-uninstaller.sh /opt/netdata

# Restore configuration files
conf_path="/opt/netdata/etc/netdata"
sudo cp -a $SRCPATH/conf/* "$conf_path"

# Restore permissions to app files
# you may need to make some file and/or directory writeable by www-data (nginx user)
sudo chown -R root: "$conf_path"

# Restore NGINX configuration
sudo cp -a $SRCPATH/nginx.conf "/etc/nginx/conf.d/${domain}.d/${app}.conf"

# Restart webserver
sudo service nginx reload
