#!/bin/bash

# Keep this path for calling _common.sh inside the execution's context of backup and restore scripts
source ../settings/scripts/_common.sh
source /usr/share/yunohost/helpers

#=================================================
# STANDARD RESTORATION STEPS
#=================================================
# RESTORE THE APP MAIN DIR
#=================================================
ynh_script_progression "Restoring Netdata configuration directory..."

ynh_restore "$install_dir/etc/netdata"

#=================================================
# INSTALL AND RESTORE THE APP CONFIGURATION
#=================================================
ynh_script_progression "Reinstalling Netdata..."

# Download, check integrity, uncompress and patch the source from app.src
NETDATA_TMPDIR="$install_dir/netdata_install"
mkdir -p $NETDATA_TMPDIR
ynh_setup_source --dest_dir="$NETDATA_TMPDIR"
GO_TMPDIR="$install_dir/go_install"
mkdir -p $GO_TMPDIR
ynh_setup_source --source_id="go" --dest_dir="$GO_TMPDIR"

export PATH="$GO_TMPDIR/bin:$PATH"
export GOPATH="$GO_TMPDIR/go/"
export HOME=${HOME:-"/root/"}
pushd "$NETDATA_TMPDIR"
    # the installer.sh script will append "netdata" after the --install-prefix arg
    ynh_hide_warnings ./netdata-installer.sh --install-prefix /var/www/ --dont-wait --disable-cloud --disable-telemetry --stable-channel
popd

ynh_safe_rm $NETDATA_TMPDIR
ynh_safe_rm $GO_TMPDIR

# Specific configuration
configure_netdata

#=================================================
# RESTORE SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Restoring system configurations related to $app..."

ynh_restore "/etc/nginx/conf.d/$domain.d/$app.conf"

yunohost service add "$app" --description "Real-time performance and health monitoring" --log "$install_dir/var/log/netdata/error.log" "$install_dir/var/log/netdata/access.log" "$install_dir/var/log/netdata/debug.log"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Reloading NGINX web server and $app's service..."

ynh_systemctl --service="$app" --action="start" --log_path="$install_dir/var/log/$app/error.log"

ynh_systemctl --service=nginx --action=reload

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Restoration completed for $app"
